image: python:3.6.5-alpine3.7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/pip

before_script:
  - python -V
  - pip install -r requirements.txt

test:
  script:
  - pytest
